### ISSUE TITLE
undefined reference to `__mingw_SEH_error_handler` in i386 build

### ISSUE THREAD

**Issue by negrutiu** [mingw-w64/mingw-w64#177]
Hi folks,
I've recently updated my msys2/mingw package and my project has started encountering the following linker error.
The error occurs only in x86 builds, while x86_64 builds complete successfully.
Any assistance would be greatly appreciated. Thank you!

## Linker error
```
[...]
ld.exe: C:/msys64/mingw32/lib\libmsvcrt.a(lib32_libmsvcrt_extra_a-i386__beginthreadex.o): in function `sse_float_exception_handler':
D:/W/B/src/mingw-w64/mingw-w64-crt/misc/i386__beginthreadex.c:28:(.text+0x8b): undefined reference to `__mingw_SEH_error_handler'
[...]
```

## Linker command
```
g++ -static -static-libgcc -static-libstdc++ -s -mwindows -Wl,--file-alignment,512 -Wl,-Map,build\urelease\NSISdl\x86-ansi\NSISdl.map -static-libgcc -static-libstdc++ -Wl,-e_DllMain@12 -shared -o build\urelease\NSISdl\x86-ansi\NSISdl.dll build\urelease\NSISdl\x86-ansi\asyncdns.o build\urelease\NSISdl\x86-ansi\connection.o build\urelease\NSISdl\x86-ansi\httpget.o build\urelease\NSISdl\x86-ansi\nsisdl.o build\urelease\NSISdl\x86-ansi\util.o $( -LD:\a\nsis\nsis\cppunit\lib -Lbuild\urelease\api\nsis $) -lpluginapi-x86-ansi -ladvapi32 -lwsock32 -luser32 -lkernel32 -Wl,--out-implib,build\urelease\NSISdl\x86-ansi\libNSISdl.a
```

## gcc version
```
gcc (Rev5, Built by MSYS2 project) 16.1.0
Copyright (C) 2026 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by lhmouse** [comment]
Looks like `__mingw_SEH_error_handler` is referenced in libmsvcrt but it's defined in libmingw32.

For the time being you can try adding `-lmingw32 -lmsvcrt` before `-ladvapi32 -lwsock32 -luser32 -lkernel32` in your command line.

**Comment by negrutiu** [comment]
Tried your suggestion, same error.
```
g++ -static -static-libgcc -static-libstdc++ -s -mwindows -Wl,--file-alignment,512 -Wl,-Map,build\urelease\NSISdl\x86-ansi\NSISdl.map -static-libgcc -static-libstdc++ -Wl,-e_DllMain@12 -shared -o build\urelease\NSISdl\x86-ansi\NSISdl.dll build\urelease\NSISdl\x86-ansi\asyncdns.o build\urelease\NSISdl\x86-ansi\connection.o build\urelease\NSISdl\x86-ansi\httpget.o build\urelease\NSISdl\x86-ansi\nsisdl.o build\urelease\NSISdl\x86-ansi\util.o $( -L.depend\cppunit\lib -Lbuild\urelease\api\nsis $) -lpluginapi-x86-ansi -lmingw32 -lmsvcrt -ladvapi32 -lwsock32 -luser32 -lkernel32 -Wl,--out-implib,build\urelease\NSISdl\x86-ansi\libNSISdl.a

ld.exe: C:/msys64/mingw32/lib/libmsvcrt.a(lib32_libmsvcrt_extra_a-i386__beginthreadex.o): in function `sse_float_exception_handler':
D:/W/B/src/mingw-w64/mingw-w64-crt/misc/i386__beginthreadex.c:28:(.text+0x8b): undefined reference to `__mingw_SEH_error_handler'
```

**Comment by lhmouse** [comment]
not sure but this is likely caused by b9ac6b67372d065a5bcd4f515b7f84118a65446b.

**Comment by lhmouse** [comment]
Try linking with `g++ -v`, and examine the output. With the bultin specs file, the linker is passed

```
-lmingw32 -lgcc -lgcc_eh -lmingwex -lmsvcrt -lkernel32
-lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 
-lmingw32 -lgcc -lgcc_eh -lmingwex -lmsvcrt -lkernel32
```

`-lmingw32` is passed twice so the issue is hidden _sometimes_. It's likely that your build system is less quirky and reveals the issue.

**Comment by lhmouse** [comment]
https://sourceforge.net/p/mingw-w64/mailman/message/59353603/

**Comment by negrutiu** [comment]
> Try linking with `g++ -v`, and examine the output. With the bultin specs file, the linker is passed
> 
> ```
> -lmingw32 -lgcc -lgcc_eh -lmingwex -lmsvcrt -lkernel32
> -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 
> -lmingw32 -lgcc -lgcc_eh -lmingwex -lmsvcrt -lkernel32
> ```
> 
> `-lmingw32` is passed twice so the issue is hidden _sometimes_. It's likely that your build system is less quirky and reveals the issue.

While playing around with `-v` I managed to link successfully by removing the `-static` argument.
Didn't touch other linker parameters (no -lmingw32 or anything else), only removed `-static` and the build succeeded.

-----

> https://sourceforge.net/p/mingw-w64/mailman/message/59353603/

Thank you for reporting the issue upstream.
I'd be happy to test the fix if someone can provide a patched version of mingw.

**Comment by negrutiu** [comment]
I confirm that the link error no longer occurs in the latest version of the msys2/mingw package.
Latest version includes git commit [4e663049 "crt: Fix linking issues for __mingw_SEH_error_handler symbol"](https://github.com/mingw-w64/mingw-w64/commit/4e663049e66ade1d1cd4061e2337236038efc1fd) which resolves the issue.
I appreciate the efforts of the maintainers in addressing this problem. Thank you, guys!
