### ISSUE TITLE
error: unknown type name 'POINTER_INPUT_TYPE'

### ISSUE THREAD

**Issue by lazka** [mingw-w64/mingw-w64#57]
Filing this mostly so I can reference it in commit. This popped up after we updated in MSYS2 from https://github.com/mingw-w64/mingw-w64/compare/90abf784a...8704184f6

```
In file included from C:/M/B/src/VTK-9.3.1/Rendering/UI/vtkWin32RenderWindowInteractor.cxx:19:
In file included from C:/M/B/src/VTK-9.3.1/Rendering/UI/vtkWin32RenderWindowInteractor.h:23:
In file included from C:/M/B/src/VTK-9.3.1/Common/Core/vtkWindows.h:46:
In file included from C:/msys64/clangarm64/include/windows.h:72:
C:/msys64/clangarm64/include/winuser.h:2965:72: error: unknown type name 'POINTER_INPUT_TYPE'
 2965 | WINUSERAPI HSYNTHETICPOINTERDEVICE WINAPI CreateSyntheticPointerDevice(POINTER_INPUT_TYPE pointerType, ULONG maxCount, POINTER_FEEDBACK_MODE mode);
      |                                                                        ^
C:/msys64/clangarm64/include/winuser.h:2965:120: error: unknown type name 'POINTER_FEEDBACK_MODE'
 2965 | WINUSERAPI HSYNTHETICPOINTERDEVICE WINAPI CreateSyntheticPointerDevice(POINTER_INPUT_TYPE pointerType, ULONG maxCount, POINTER_FEEDBACK_MODE mode);
      |                                                                                                                        ^
C:/msys64/clangarm64/include/winuser.h:2966:93: error: unknown type name 'POINTER_TYPE_INFO'
 2966 | WINUSERAPI WINBOOL WINAPI InjectSyntheticPointerInput(HSYNTHETICPOINTERDEVICE device, CONST POINTER_TYPE_INFO* pointerInfo, UINT32 count);
      |                                                                                             ^
```

Only affects clangarm64 in MSYS2, which is the only env targeting win10+ (`--with-default-win32-winnt=0xA00`) so I suspect 6cfc1fd2ca2fdbbb8d6570084970bea2ef100d2e

**Comment by lazka** [comment]
I can confirm that reverting 6cfc1fd2ca2fdbbb8d fixes things

**Comment by lazka** [comment]
https://sourceforge.net/p/mingw-w64/mailman/message/58805108/

**Comment by Biswa96** [comment]
This is fixed, right?

**Comment by lazka** [comment]
Yes, fixed by eea00c008763d4ddedb8598ba0963191e7ebf45d
